import { useContext, useMemo, useState } from 'react'
import { Check, Edit3, Filter, Plus, Search, Trash2, X } from 'lucide-react'
import { AppContext } from '../App'

export default function Tasks(){
 const {tasks,addTask,updateTask,deleteTask}=useContext(AppContext)
 const [query,setQuery]=useState(''); const [filter,setFilter]=useState('all'); const [open,setOpen]=useState(false); const [editing,setEditing]=useState(null)
 const visible=useMemo(()=>tasks.filter(t=>(t.title+' '+(t.subject||'')).toLowerCase().includes(query.toLowerCase())).filter(t=>filter==='all'||filter==='completed'&&t.completed||filter==='pending'&&!t.completed||filter===t.priority?.toLowerCase()),[tasks,query,filter])
 const submit=async data=>{ if(editing){await updateTask(editing._id,data)} else {await addTask(data)}; setOpen(false);setEditing(null) }
 return <>
  <PageTitle eyebrow="TASK MANAGEMENT" title="Tasks" desc="Capture assignments, deadlines and study work in one place." action={<button className="primary-btn" onClick={()=>setOpen(true)}><Plus size={17}/> New task</button>}/>
  <div className="toolbar"><div className="search-box"><Search size={17}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search tasks…"/></div><div className="filter"><Filter size={16}/><select value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All tasks</option><option value="pending">Pending</option><option value="completed">Completed</option><option value="high">High priority</option><option value="medium">Medium priority</option><option value="low">Low priority</option></select></div></div>
  <div className="task-cards">{visible.length?visible.map(t=><TaskCard key={t._id} task={t} onEdit={()=>{setEditing(t);setOpen(true)}} onDelete={()=>deleteTask(t._id)} onToggle={()=>updateTask(t._id,{completed:!t.completed})}/>):<div className="empty"><Search size={28}/><strong>No matching tasks</strong><span>Try a different search or add a new task.</span></div>}</div>
  {open&&<TaskModal task={editing} onClose={()=>{setOpen(false);setEditing(null)}} onSubmit={submit}/>} 
 </>
}
function PageTitle({eyebrow,title,desc,action}){return <div className="page-title"><div><span className="eyebrow">{eyebrow}</span><h1>{title}</h1><p>{desc}</p></div>{action}</div>}
function TaskCard({task,onEdit,onDelete,onToggle}){return <article className={`task-card ${task.completed?'done':''}`}><button className="check-btn" onClick={onToggle}>{task.completed?<Check size={16}/>:null}</button><div className="task-info"><h3>{task.title}</h3><p>{task.description||'No description provided.'}</p><div className="meta"><span>{task.subject||'General'}</span><span className={`priority ${task.priority?.toLowerCase()}`}>{task.priority}</span>{task.dueDate&&<span>Due {new Date(task.dueDate).toLocaleDateString()}</span>}</div></div><div className="card-actions"><button onClick={onEdit} title="Edit"><Edit3 size={16}/></button><button onClick={onDelete} title="Delete"><Trash2 size={16}/></button></div></article>}
function TaskModal({task,onClose,onSubmit}){const [form,setForm]=useState({title:task?.title||'',description:task?.description||'',subject:task?.subject||'',priority:task?.priority||'Medium',dueDate:task?.dueDate?task.dueDate.slice(0,10):''}); const [busy,setBusy]=useState(false); const save=async e=>{e.preventDefault();setBusy(true);try{await onSubmit(form)}finally{setBusy(false)}};return <div className="modal-backdrop"><form className="modal" onSubmit={save}><div className="modal-head"><div><span className="eyebrow">{task?'EDIT TASK':'NEW TASK'}</span><h2>{task?'Update task':'Create task'}</h2></div><button type="button" className="icon-btn" onClick={onClose}><X size={19}/></button></div><label>Task title<input required value={form.title} onChange={e=>setForm({...form,title:e.target.value})}/></label><label>Description<textarea rows="3" value={form.description} onChange={e=>setForm({...form,description:e.target.value})}/></label><div className="two-col"><label>Subject<input value={form.subject} onChange={e=>setForm({...form,subject:e.target.value})}/></label><label>Priority<select value={form.priority} onChange={e=>setForm({...form,priority:e.target.value})}><option>High</option><option>Medium</option><option>Low</option></select></label></div><label>Due date<input type="date" value={form.dueDate} onChange={e=>setForm({...form,dueDate:e.target.value})}/></label><div className="modal-actions"><button type="button" className="secondary-btn" onClick={onClose}>Cancel</button><button className="primary-btn" disabled={busy}>{busy?'Saving…':'Save task'}</button></div></form></div>}
